# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "2.7.12"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

os:
  - linux
# command to run tests, e.g. python setup.py test
script: python setup.py test

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: wannaphong
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: wannaphongcom/pythainlp
    #condition: $TOXENV == py35
